# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    id: nopaste
    main: cmd/nopaste/main.go
    binary: nopaste
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - env:
      - CGO_ENABLED=0
    id: irc-msgr
    main: cmd/irc-msgr/main.go
    binary: irc-msgr
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
  - env:
      - CGO_ENABLED=0
    id: nopaste-cli
    binary: nopaste-cli
    main: cmd/nopaste-cli/nopaste-cli.go
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
